/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SupportedFeatures {
  keyboard: boolean
  images: boolean
  loadFrame: boolean
  compositeFrame: boolean
}
export interface WindowSize {
  cols: number
  rows: number
  width: number
  height: number
}
/** Enable features for the terminal that are necessary for Awrit */
export declare function termEnableFeatures(): SupportedFeatures
/** Disable previously enabled features for the terminal that are necessary for Awrit */
export declare function termDisableFeatures(features: SupportedFeatures): void
/** Get the current terminal window size */
export declare function getWindowSize(): WindowSize
/** Returns true if called inside a Tmux session, false otherwise. */
export declare function isTmux(): boolean
/** Send the given sequence directly to the client terminal passing through tmux */
export declare function passthroughTmux(sequence: string): void
export declare function writeMaybeTmux(sequence: string): void
export type TermEvent =
  { eventType: 'key', keyEvent: KeyEvent } |
  { eventType: 'mouse', mouseEvent: MouseEvent } |
  { eventType: 'focus', focusGained?: boolean, focusLost?: boolean } |
  { eventType: 'resize', resize: TermResize } |
  { eventType: 'paste', paste: string } |
  { eventType: 'escape', escape: TermEscape } |
  { eventType: 'graphics', graphics: KittyGraphics }
export interface KeyEvent {
  /** Key code in Electron accelerator format (lowercase) */
  code: string
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift' | 'meta' | 'capsLock' | 'numLock' | 'left' | 'right' | 'isAutoRepeat')[]
  /** True for keydown and repeat events, false for keyup */
  down: boolean
  /** True for keys that should have an Electron char event */
  isCharEvent: boolean
}
export interface MouseEvent {
  kind: 'mouseDown' | 'mouseUp' | 'mouseMove' | 'scrollUp' | 'scrollDown' | 'scrollLeft' | 'scrollRight'
  button?: 'left' | 'middle' | 'right' | 'fourth' | 'fifth' | null
  x: number
  y: number
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift')[]
}
export interface TermResize {
  columns: number
  rows: number
}
export interface TermEscape {
  kind: 'osc' | 'apc' | 'dcs' | 'pm'
  text: string
}
export interface KittyGraphics {
  id: string
  status: string
}
export declare function listenForInput(callback: (arg: TermEvent) => void, waitMs?: number | undefined | null): () => void
export interface DirtyRect {
  x: number
  y: number
  width: number
  height: number
}
export declare class ShmGraphicBuffer {
  /** Creates a new shared memory buffer with a unique name with the provided size */
  constructor(size: number)
  /** Returns the shared memory name as a base64 encoded string */
  get nameBase64(): string
  /** Creates and truncates the shared memory segment to the specified size, filling it with zeros */
  writeEmpty(): void
  /** Writes an image buffer to the shared memory at the specified dirty rectangle */
  write(buffer: Buffer, imageWidth: number, dirtyRect?: DirtyRect | undefined | null): void
}
