/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ShmGraphicBuffer {
  /** Creates a new shared memory buffer with a unique name with the provided size */
  constructor(size: number)
  /**
   * Writes the raster, but refuses if the terminal has not yet read the
   * previous contents of this segment.
   *
   * `O_EXCL` is the whole mechanism: it succeeds only when the name is free,
   * which — given the terminal unlinks a `t=s` segment once it has read it —
   * is exactly when the previous frame has been consumed. Returns
   * `Ok(false)` while the segment is still in flight, so the caller can pick
   * another one instead of truncating a segment out from under a live read.
   */
  tryWrite(buffer: Buffer, imageWidth: number): boolean
  /** Returns the shared memory name as a base64 encoded string */
  get nameBase64(): string
  /** Creates and truncates the shared memory segment to the specified size, filling it with zeros */
  writeEmpty(): void
  /**
   * Cost of the last `write_texture`, in ms: (shm map, convert, unmap).
   * Diagnostics only — reading it costs a lock, so it is off the hot path in JS.
   */
  timings(): number[]
  /** Writes an image buffer to the shared memory at the specified dirty rectangle */
  write(buffer: Buffer, imageWidth: number, dirtyRect?: DirtyRect | undefined | null): void
  /**
   * Reads a texture pinned by `pin_texture` into the shared memory, skipping
   * the CPU-side `NativeImage` copy entirely. Row padding is dropped.
   *
   * Consumes the pin. Prefer this over `write_texture` when the caller can
   * release the Electron texture before reading, so the texture is not held
   * for the duration of the read.
   */
  writeTexture(id: number, swap: boolean): void
}

export interface DirtyRect {
  x: number
  y: number
  width: number
  height: number
}

/**
 * napi boundary: `Option<Buffer>` so a `null` return is a direct "fall back
 * to Electron" signal to the caller.
 */
export declare function encodePngOpaque(bgra: Buffer, width: number, height: number): Buffer | null

/** napi boundary for the indexed/palette path. */
export declare function encodePngPal(bgra: Buffer, width: number, height: number): Buffer | null

/** Get tmux pane size with 250ms caching. Falls back to regular window_size if not in tmux. */
export declare function getTmuxPaneSize(): WindowSize

/** Get the current terminal window size */
export declare function getWindowSize(): WindowSize

/** Returns true if called inside a Tmux session, false otherwise. */
export declare function isTmux(): boolean

export interface KeyEvent {
  /** Key code in Electron accelerator format (lowercase) */
  code: string
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift' | 'meta' | 'capsLock' | 'numLock' | 'left' | 'right' | 'isAutoRepeat')[]
  /** True for keydown and repeat events, false for keyup */
  down: boolean
  /** True for keys that should have an Electron char event */
  isCharEvent: boolean
}

export interface KittyGraphics {
  id: string
  status: string
}

export declare function listenForInput(callback: (arg: TermEvent) => void, waitMs?: number | undefined | null): () => void

export interface MouseEvent {
  kind: 'mouseDown' | 'mouseUp' | 'mouseMove' | 'scrollUp' | 'scrollDown' | 'scrollLeft' | 'scrollRight'
  button?: 'left' | 'middle' | 'right' | 'fourth' | 'fifth' | null
  x: number
  y: number
  /** Array of modifier strings in Electron accelerator format */
  modifiers: ('ctrl' | 'alt' | 'shift')[]
}

/** Send the given sequence directly to the client terminal passing through tmux */
export declare function passthroughTmux(sequence: string): void

/**
 * Pins a GPU shared texture's plane (a dmabuf from
 * `webPreferences.offscreen.useSharedTexture`) and returns a handle for
 * `ShmGraphicBuffer::write_texture`.
 *
 * Costs ~0.2ms, against ~20ms for the read it enables, so the caller can
 * release the Electron texture immediately afterwards. The fd is dup'd, so the
 * allocation outlives Electron dropping its own reference; `unpin_texture`
 * drops it. `stride` is the row stride in bytes, GPU-aligned and therefore
 * larger than `width * 4`.
 */
export declare function pinTexture(fd: number, width: number, height: number, stride: number, offset: number, size: number): number

export interface SupportedFeatures {
  keyboard: boolean
  images: boolean
  loadFrame: boolean
  compositeFrame: boolean
}

/** Disable previously enabled features for the terminal that are necessary for Awrit */
export declare function termDisableFeatures(features: SupportedFeatures): void

/** Enable features for the terminal that are necessary for Awrit */
export declare function termEnableFeatures(): SupportedFeatures

export interface TermEscape {
  kind: 'osc' | 'apc' | 'dcs' | 'pm'
  text: string
}

export type TermEvent =
  { eventType: 'key', keyEvent: KeyEvent } |
  { eventType: 'mouse', mouseEvent: MouseEvent } |
  { eventType: 'focus', focusGained?: boolean, focusLost?: boolean } |
  { eventType: 'resize', resize: TermResize } |
  { eventType: 'paste', paste: string } |
  { eventType: 'escape', escape: TermEscape } |
  { eventType: 'graphics', graphics: KittyGraphics }

export interface TermResize {
  columns: number
  rows: number
}

/** Returns the DCS sequence to begin tmux passthrough */
export declare function tmuxBeginPassthrough(): string

/** Returns the DCS sequence to end tmux passthrough */
export declare function tmuxEndPassthrough(): string

/** Wrap a string with tmux passthrough DCS sequences, escaping ESC characters */
export declare function tmuxPassthrough(buffer: string): string

/** Returns the CSI sequence for the requested tmux extended-keys mode */
export declare function tmuxSetExtendedKeysMode(mode: string): string

/**
 * Unmap a pinned texture without reading it. Safe with a stale or already
 * consumed id, so callers can unpin unconditionally on the error path.
 */
export declare function unpinTexture(id: number): void

export interface WindowSize {
  cols: number
  rows: number
  width: number
  height: number
}

/** Wrap a sequence with tmux passthrough DCS sequences in one call */
export declare function wrapTmuxPassthrough(sequence: string): string

export declare function writeMaybeTmux(sequence: string): void
