[vars]
electron_dir = "{{ [config_root, 'node_modules', 'electron'] | join_path }}"
electron_path = "{{ [vars.electron_dir, 'path.txt' ] | join_path }}"
electron_dist = "{{ [vars.electron_dir, 'dist' ] | join_path }}"
electron_cache = "{{ [xdg_cache_home, 'electron'] | join_path }}"
electron_plist = "{{ [vars.electron_dist, 'Electron.app', 'Contents', 'Info.plist' ] | join_path }}"
awrit_native_dir = "{{ [config_root, 'awrit-native-rs',] | join_path }}"

[env]

[tools]
bun = "1.4.0"
rust = "stable"
cargo-binstall = "latest"
pre-commit = "latest"
cocogitto = "latest"

[hooks]
postinstall = { task = "postinstall" }

[tasks.postinstall]
quiet = true
hide = true
run = [
  { task = "setup" },
]

[settings]
cargo.binstall = true
cargo.binstall_only = true
task.quiet = true

##########################################################
# Setup environment
[tasks."setup"]
description = "setup a developpment environment"
run = [
  "{% if not env.GITHUB_WORKFLOW %} mise run 'pc:init' {% endif %}",
  "bun install",
  { task = "setup:build" },
  { task = "setup:verify-electron" },
  { task = "setup:patch-electron" },
]

[tasks."setup:verify-electron"]
description = "If bun's extract-zip failed fall back to `ouch`"
hide = true
run = '''
{% if vars.electron_path is not file %}
  {% set cache = exec(command="find " ~ vars.electron_cache ~ " -name electron-*.zip -print -quit") %}
  {% if cache %}
    mise run setup:unzip-electron {{ cache }}
  {% else %}
    echo "failed to install electron"
    exit 1
  {% endif %}
{% endif %}
'''

[tasks."setup:unzip-electron"]
hide = true
tools."aqua:ouch-org/ouch" = "latest"
usage = '''
arg "<file>"
'''
run = '''
ouch decompress {{ usage.file }} -d {{ vars.electron_dist }} -r -q -y
printf 'electron' >{{ vars.electron_path }}
'''

[tasks."setup:patch-electron"]
description = "on macos patch Electron.app to not display in the Dock"
hide = true
run = '''
{% if os() == "macos" %}
  sed -i '' 's/<\/dict>/    <key>LSUIElement<\/key>\n    <true\/>\n<\/dict>/' {{ vars.electron_plist }} || true
{% endif %}
'''

[tasks."setup:build"]
description = "build awrit-native-rs package"
dir = "{{ vars.awrit_native_dir }}"
env.BUILD_TARGET = { default = "" }
run = '''
{% if env.GITHUB_WORKFLOW %}
  bun napi build --platform --release --target {{ env.BUILD_TARGET }}
  {% if env.BUILD_TARGET == "x86_64-apple-darwin" %}
    rm awrit-native-rs.darwin-arm64.node
  {% endif %}
{% else %}
  bun napi build --platform --release
{% endif %}
  bun scripts/fix-types.js
'''

[tasks."setup:clean"]
alias = "clean"
description = "clean-up source tree from installed and generated artifacts"
confirm = "this action is irreversible, continue?"
run = [
  # root
  "rm -rf ./node_modules 2>/dev/null || :",
  "rm -rf ./dist 2>/dev/null || :",
  "rm -rf ./.bun 2>/dev/null || :",
  "rm -f ./awrit_error.txt 2>/dev/null || :",
  # awrit-native-rs
  "rm -rf ./awrit-native-rs/node_modules 2>/dev/null || :",
  "rm -rf ./awrit-native-rs/target 2>/dev/null || :",
  "rm -f ./awrit-native-rs/package-lock.json 2>/dev/null || :",
  "rm -f ./awrit-native-rs/index.js 2>/dev/null || :",
  "rm -f ./awrit-native-rs/index.d.ts 2>/dev/null || :",
  "rm -f ./awrit-native-rs/awrit-native-rs.linux-x64-gnu.node 2>/dev/null || :",
  # crates
  "rm -rf ./awrit-native-rs/crates/crossterm/target 2>/dev/null || :",
  "rm -rf ./awrit-native-rs/crates/crossterm/Cargo.lock 2>/dev/null || :",
  "rm -rf ./awrit-native-rs/crates/bgra-to-rgba/target 2>/dev/null || :",
  # runner
  "rm -rf ./src/runner/node_modules 2>/dev/null || :",
]


##########################################################
# Dev commands
[tasks."dev:format"]
alias = "format"
description = "check code formatting"
usage = '''
arg "[files]" help="files to format" var=#true default="."
flag "--write" help="format the file(s)" default=#false
'''
run = '''
{% if usage.write %}
  biome format --write {{ usage.files | join(sep=' ') }}
{% else %}
  biome check --linter-enabled=false --assist-enabled=false {{ usage.files | join(sep=' ') }}
{% endif %}
'''

[tasks."dev:lint"]
alias = "lint"
description = "lint code"
usage = '''
arg "[files]" help="files to lint" var=#true default="./src"
flag "--write" help="apply safe fixes" default=#false
flag "--unsafe" help="also apply unsafe fixes" default=#false
'''
run = '''
{% if usage.write %}
  {% if usage.unsafe %}
    biome lint --write --unsafe {{ usage.files | join(sep=' ') }}
  {% else %}
    biome lint --write {{ usage.files | join(sep=' ') }}
  {% endif %}
{% else %}
  biome lint {{ usage.files | join(sep=' ') }}
{% endif %}
'''

[tasks."dev:typecheck"]
alias = "typecheck"
description = "verify typescript types"
run = "tsc --noEmit --skipLibCheck"

[tasks."dev:start"]
alias = "start"
description = "start [todo]"
run = "electron dist/index.cjs"

[tasks."dev:audit"]
alias = "audit"
description = "audit node installed packages for vulnerabilities"
usage = '''
arg "<level>" help="audit level" {
  choices "low" "moderate" "high" "critical"
  default "high"
}
flag "--show-fix" help="show available fixes" default=#false
'''
run = '''
{% if usage.show_fix %}
  bun audit fix --audit-level={{ usage.level }} --prod --dry-run
{% else %}
  bun audit --audit-level={{ usage.level }} --prod
{% endif %}
'''

##########################################################
# Tests
[tasks."test:all"]
alias = "test"
description = "run the tests suite"
run = "bun test"

[tasks."test:input"]
description = "run interactive input test"
run = "bun run ./src/tty/inputTest.ts"

[tasks."test:gfx"]
description = "run graphics test"
run = "bun run ./src/tty/graphicsTest.ts"


##########################################################
# Pre-commit
[tasks."pc:init"]
description = "initialize pre-commit"
silent = "stdout"
run = "pre-commit install --install-hooks"

[tasks."pc:update"]
description = "update pre-commit hooks"
depends = ["pc:init"]
run = "pre-commit autoupdate"

[tasks."pc:check"]
description = "run pre-commit hooks"
depends = ["pc:init"]
run = "pre-commit run --all-files"

[tasks."pc:clean"]
description = "cleanup pre-commit hooks"
depends = ["pc:init"]
run = ["pre-commit clean", "pre-commit gc"]

##########################################################
# Version
[tasks."version:suggest"]
description = "suggest next version tag"
run = "cog bump --dry-run --auto --skip-untracked --disable-bump-commit"

[tasks."version:get"]
description = "output actual version tag"
run = "cog -v get-version --include-prereleases --tag"

[tasks."version:bump-pkg"]
description = "bump version in package.json"
hide = true
usage = '''
arg "<version>"
'''
run = "bun pm version {{ usage.version }} --no-git-tag-version --force"

##########################################################
# CI
[tasks."ci:version-bump"]
description = "make CHANELOG.md, bump version and commit if in CI"
env = { "GITHUB_WORKFLOW" = { required = "task only allowed in CI workflow" } }
hide = true
run = "cog bump --auto"

[tasks."ci:cover-badge"]
description = "generate a coverage.svg badge"
env = { "GITHUB_WORKFLOW" = { required = "task only allowed in CI workflow" } }
hide = true
tools."pipx:genbadge[coverage]" = "latest"
tools."pipx:lcov_cobertura" = "latest"
run = "lcov_cobertura lcov.info && genbadge coverage -i coverage.xml -o assets/coverage.svg"

##########################################################
# Runner
[tasks.awrit]
usage = '''
arg "[args]" var=#true help="any arguments to provide to awrit"
'''
run = "bun run {{ config_root }}/src/runner {{ usage.args | join(sep=' ') }} 2>{{ config_root }}/awrit_error.txt"
